name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
description: Automatically checks pull requests changes with clang-tidy, clang-format, and cppcheck and posts the comment with result.
author: ArtificialAmateur
branding:
  icon: alert-circle
  color: green
inputs:
  build_path:
    description: 'Path to executable'
    required: true
  make_options:
    description: 'Makefile options to be used by clang-tidy'
    required: false
  ignore_files:
    description: 'A regex which clang-tidy uses to ignore files'
    required: false
  header_filter:
    description: 'Header filter regex to be used by clang-tidy'
    required: false
    default: '.*'
  config_file:
    description: 'path to configuration file'
    required: false
    default: '.clang-tidy'
  cppcheck_options:
    description: 'Extra options to pass to cppcheck, separated by spaces'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
