name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
description: Automatically checks pull requests changes with clang-tidy, clang-format, and cppcheck and posts the comment with result.
author: ArtificialAmateur
branding:
  icon: alert-circle
  color: green
inputs:
  build_path:
    description: 'Path to executable'
    required: true 
  make_options:
    description: 'Makefile options to be used by clang-tidy'
    required: false
  ignore_files:
    description: 'A regex which clang-tidy uses to ignore files'
    required: false
  header_filter:
    description: 'Header filter regex to be used by clang-tidy'
    required: false
    default: '.*'
  checks:
    description: 'list of checks to be used by clang-tidy'
    required: false 
    default: 'bugprone-*,performance-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*,readability-*,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-bounds-constant-array-index,-clang-diagnostic-unknown-warning-option,-clang-diagnostic-unknown-pragmas'

runs:
  using: 'docker'
  image: 'Dockerfile'
